version: '{build}'
branches:
  only:
  - master

clone_folder: c:\projects\zlib

image:
  #- Visual Studio 2015
  - Visual Studio 2017

configuration:
#  - Release
  - Debug

platform:
  - x64

environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
  - set version=1.2.11
  - set ipath=p:\prj\libs\zlib\%version%
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator64="Visual Studio 15 2017%arch%" & set generator="Visual Studio 15 2017")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator64="Visual Studio 14 2015%arch%" & set generator="Visual Studio 14 2017")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator64="Visual Studio 12 2013%arch%" & set generator="Visual Studio 12 2017")
  - echo %generator%

build_script:
  - cd
  - curl -k -O https://zlib.net/zlib-%version%.tar.gz
  - 7z x zlib*.gz
  - 7z x zlib*.tar
  - cd zlib-%version%
  - cmake --version

  - md c:\projects\zlib\install
  - echo c:\projects\zlib\install
  - cmd: SUBST "P:" c:\projects\zlib\install
  - dir p:

  #- cmake -DCMAKE_BUILD_TYPE=Release .. -G %generator%

  #- echo cmake .. -G %generator%
  #- cmake .. -G %generator%
  ##- echo cmake .. -G %generator%
  
  ##- cmake -DCMAKE_INSTALL_PREFIX=%ipath%\tmp .. -G %generator%
  ##- cmake  --build . --config Release
  ##- cmake  --build . --config Debug
  ##- cmake --build . --config Debug --target INSTALL
  ##- cmake --build . --config Release --target INSTALL
  ##- cd ..
  ##- dir/s *.exe *.lib *.pdb

  - cd
  - md build64md
  - cd build64md
  - cmake -DCMAKE_INSTALL_PREFIX=%ipath%\tmp .. -G %generator64%
  - cmake --build . --config Debug --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x64 mdd -s include lib\zlibstaticd.lib
  - cmake --build . --config Release --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x64 md  -s include lib\zlibstatic.lib

  - cd
  - md ..\build32md
  - cd ..\build32md
  - cmake -DCMAKE_INSTALL_PREFIX=%ipath%\tmp .. -G %generator%
  - cmake --build . --config Debug --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x86 mdd -s include lib\zlibstaticd.lib
  - cmake --build . --config Release --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x86 md  -s include lib\zlibstatic.lib

  - cd
  - md ..\build64mt
  - cd ..\build64mt
  - cmake -DCMAKE_INSTALL_PREFIX=%ipath%\tmp -DCMAKE_C_FLAGS_DEBUG="/MTd /Zi /Ob0 /Od /RTC1" -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /Ob2 /DNDEBUG" .. -G %generator%
  - cmake --build . --config Debug --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x64 mtd -s include lib\zlibstaticd.lib
  - cmake --build . --config Release --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x64 mt  -s include lib\zlibstatic.lib

  - cd
  - md ..\build32mt
  - cd ..\build32mt
  - cmake -DCMAKE_INSTALL_PREFIX=%ipath%\tmp -DCMAKE_C_FLAGS_DEBUG="/MTd /Zi /Ob0 /Od /RTC1" -DCMAKE_C_FLAGS_RELEASE="/MT /O2 /Ob2 /DNDEBUG" .. -G %generator%
  - cmake --build . --config Debug --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x86 mtd -s include lib\zlibstaticd.lib
  - cmake --build . --config Release --target INSTALL
  - cmd: ..\..\cfiles.bat zlib %version% x86 mt  -s include lib\zlibstatic.lib



  - set
  - cd c:\projects\zlib
  - dir
  - dir p:\ /s
  - cd /d p:\
  - 7z a zlib-%version%.zip prj\libs\zlib\%version%\include prj\libs\zlib\%version%\lib
  - 7z l zlib-%version%.zip


artifacts:
  - path: '**\*.zip'
#  - path: '**\*.lib'


