version: '{build}'
branches:
  only:
  - master

clone_folder: c:\projects\zlib

image:
  #- Visual Studio 2015
  - Visual Studio 2017

configuration:
#  - Release
  - Debug

platform:
  - x64

environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
  - set version=1.2.11
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - echo %generator%


build_script:
  - cd
  - curl -k -O https://zlib.net/zlib-%version%.tar.gz
  - 7z x zlib*.gz
  - 7z x zlib*.tar
  - cd zlib-%version%
  - cmake --version

  - md build
  - cd build

  - md c:\projects\zlib\install
  - echo c:\projects\zlib\install
  - cmd/c subst p: c:\projects\zlib\install
  - dir p:
  #- cmake -DCMAKE_BUILD_TYPE=Release .. -G %generator%

  #- echo cmake .. -G %generator%
  #- cmake .. -G %generator%
  ##- echo cmake .. -G %generator%
  ##- cmake -DCMAKE_INSTALL_PREFIX=p:\prj\libs\zlib .. -G %generator%
  ##- cmake  --build . --config Release
  ##- cmake  --build . --config Debug
  ##- cmake --build . --config Release --target INSTALL
  ##- cd ..
  ##- dir/s *.exe *.lib *.pdb

  - cd c:\projects\zlib
  - dir
  - dir p:\

#artifacts:
#  - path: '**\*.exe'
#  - path: '**\*.lib'


